name: Build Action

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential clang lld cmake ninja-build libboost-all-dev libssl-dev libzmq3-dev

      - name: Get LLVM branch hash
        run: git ls-remote https://github.com/llvm/llvm-project.git $(cat libcashew/CMakeLists.txt | sed -n 's/ *GIT_TAG\ *\(.*\)/\1/p') > llvm_branch_hash.txt

      - name: Build cache
        uses: actions/cache@v3
        with:
          path: |
            build
          key: ${{ runner.os }}-cmake-${{ hashFiles('llvm_branch_hash.txt') }}

      - name: Build
        run: |
          mkdir build && cd build && cmake .. && ninja
